on:
  push:
    branches:
      - main
name: Deploy
jobs:
  FTP-Deploy-Action1:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_ORDER_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_ORDER_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_ORDER_PASSWORD }}
          LOCAL_DIR: ./laravel/app/
          REMOTE_DIR: /app/
  FTP-Deploy-Action2:
    name: FTP-Deploy-Action2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_ORDER_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_ORDER_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_ORDER_PASSWORD }}
          LOCAL_DIR: ./laravel/public/
          REMOTE_DIR: /public/
  FTP-Deploy-Action3:
    name: FTP-Deploy-Action3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_ORDER_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_ORDER_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_ORDER_PASSWORD }}
          LOCAL_DIR: ./laravel/resources/
          REMOTE_DIR: /resources/
  FTP-Deploy-Action4:
    name: FTP-Deploy-Action4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_ORDER_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_ORDER_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_ORDER_PASSWORD }}
          LOCAL_DIR: ./laravel/routes/
          REMOTE_DIR: /routes/
